apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdaemon
  labels:
    app: nginxdaemon
spec:
  selector:
    matchLabels:
      name: nginx-pod
  template:
    metadata:
      labels:
        name: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx
